services:
    publish-test:
        build: .
        environment:
            PSGALERY: $PSGALERY_KEY
        command: pwsh -NonInteractive -File ./util/publish-prepare.ps1 -CompileDoc -CheckVersion
        
        