name: Publicar
on: 
    push:
        tags:
            - v*

jobs:

  Tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  Publish:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Publish
        shell: pwsh
        env:
          PSGALERY_KEY: ${{ secrets.PSGALERY_KEY }}
        run: ./util/publish-prepare.ps1 -CompileDoc -CheckVersion -Publish
        